### ISSUE TITLE
Unable to load app in telegram test account

### ISSUE THREAD

**Issue by Th0rgal** [Telegram-Mini-Apps/reactjs-template#11]
I'm encountering an issue when trying to load my webapp on Telegram using a local setup, following the instructions provided in the [Telegram Mini Apps documentation](https://docs.telegram-mini-apps.com/platform/test-environment) to create a test environment. I got the same issue when trying on production bot with production app deployed on vercel.

## Steps to Reproduce:

- Set up the webapp locally using the instructions from the Telegram Mini Apps documentation.
- Use either ngrok or a self-signed SSL certificate to expose the local server.
Attempt to load the webapp on Telegram using a test account.

## Expected Behavior:
The webapp should load correctly without any errors.

## Actual Behavior:
The webapp fails to load and keeps loading indefinitely. The following error is observed in the console:
```
TypeError: undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')
```

## Environment:
- Local server setup using ngrok/self-signed SSL certificate
- Test environment as described in the Telegram Mini Apps documentation

<img width="1470" alt="Screenshot 2024-07-03 at 14 09 04" src="https://github.com/Telegram-Mini-Apps/reactjs-template/assets/41830259/1a9b1820-d665-4da8-891d-cd8e6224d1e9">

**Comment by heyqbnk** [comment]
Seems like Telegram is sending an event, when the application is not even loaded. Try running the code not in the test environment

**Comment by Th0rgal** [comment]
Hey, actually I tried loading it in normal environment too with the production build but this didn't work. If you want to try my final build is accessible at ~~redacted~~

**Comment by Th0rgal** [comment]
Update: I also tried with nextjs template, both in prod and test and it didn't work. I will try with telegram sdk.

**Comment by Th0rgal** [comment]
Update: I actually started telegram beta for mac from Downloads directly, I moved it to Applications, it prompted me to update which I did, and now I can load the webview
