### ISSUE TITLE
I can't submit a local https link to BotFather

### ISSUE THREAD

**Issue by rayyu6** [Telegram-Mini-Apps/reactjs-template#12]
Hi there.

I followed the instructions in the README to start `https://localhost:5173/reactjs-template` locally. However, when I tried to submit this URL as the App URL to botFather, it wouldn't allow me to do so.

<img width="814" alt="image" src="https://github.com/Telegram-Mini-Apps/reactjs-template/assets/158121031/596632c8-6bc1-4065-930d-3b830ba52f92">

**Comment by ghost** [comment]
[Expose dev server](https://github.com/Telegram-Mini-Apps/reactjs-template?tab=readme-ov-file#expose-dev-server) or use [ngrok](https://ngrok.com/)

**Comment by heyqbnk** [comment]
README.md was updated. Thank you for report.
