### ISSUE TITLE
pnpm run dev 【Run Error】

### ISSUE THREAD

**Issue by superjiangs** [Telegram-Mini-Apps/reactjs-template#3]
After I installed the dependencies, I encountered an error during startup
![WX20240528-160015@2x](https://github.com/Telegram-Mini-Apps/reactjs-template/assets/26242617/8faa1e54-18b3-432f-9905-9982ebce8566)

**Comment by heyqbnk** [comment]
To fix it, you should remove the `server.host` Vite config option.

**Comment by superjiangs** [comment]
If I want to start in TMA, how should I configure it?

**Comment by heyqbnk** [comment]
Read [guides](https://docs.telegram-mini-apps.com/platform/creating-new-app), please.
