### ISSUE TITLE
How to prevent the app from closing on swipe or how to make the app fixed and prevent from closing?

### ISSUE THREAD

**Issue by adizh** [Telegram-Mini-Apps/reactjs-template#6]
The mini app closes down on swipe, is there any way to make it fixed or sticky? I tried to use enableConfirmation() and useViewport() hook. But the first method just confirm the closing behavior, with the useViewport() I tried to listen to change event, but still no result, there is now way to make the app sticky and close it only on user request . I wanted to do prevent the app from being closed on swipe, when users change the viewport just to make sure the app will stay fixed

**Comment by heyqbnk** [comment]
Not related to the the template. Better asking in the [@devs](https://t.me/devs) chat
