### ISSUE TITLE
when i open in tg mini app

### ISSUE THREAD

**Issue by Web3-Duck** [Telegram-Mini-Apps/reactjs-template#7]
i use 
const { initDataRaw, initData } = retrieveLaunchParams();

get some error .
Unable to retrieve launch parameters from any known source.

**Comment by heyqbnk** [comment]
Launch the application inside Telegram or mock it using the mockTelegramEnv function.

https://docs.telegram-mini-apps.com/packages/tma-js-sdk/environment
